### PR TITLE
Has one: direction option

### LINKED ISSUE #300: broken has_one for ActiveRecord has_one association
``` ruby
jsonapi_resources :authors do
    jsonapi_relationships
end
```

``` ruby
class AuthorResource < JSONAPI::Resource
  has_one :author_detail
end

class AuthorDetailResource < JSONAPI::Resource
end
```

``` ruby
class Author < ActiveRecord::Base
  has_one :author_detail
end

class AuthorDetail < ActiveRecord::Base
  belongs_to :author
end
```

when i trying to fetch resource it fails with:

```
Started GET "/authors/1" for 127.0.0.1 at 2015-07-09 00:38:46 +0300
  ActiveRecord::SchemaMigration Load (0.4ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by AuthorsController#show as API_JSON
  Parameters: {"id"=>"1"}
  Author Load (0.4ms)  SELECT  "authors".* FROM "authors" WHERE "authors"."id" = $1  ORDER BY "authors"."id" ASC LIMIT 1  [["id", 1]]
Completed 500 Internal Server Error in 17ms

NameError (undefined method `author_detail_id' for class `Author'):
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource.rb:678:in `method'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource.rb:678:in `block (2 levels) in _associate'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:285:in `foreign_key_value'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:235:in `has_one_linkage'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:261:in `link_object_has_one'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:276:in `link_object'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:159:in `block in relationship_data'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:151:in `each'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:151:in `each_with_object'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:151:in `relationship_data'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:116:in `object_hash'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:95:in `process_primary'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:34:in `serialize_to_hash'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/response_document.rb:100:in `results_to_hash'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/response_document.rb:11:in `contents'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/acts_as_resource_controller.rb:138:in `render_results'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/acts_as_resource_controller.rb:159:in `process_request_operations'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/acts_as_resource_controller.rb:18:in `show'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
  activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /home/senid/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /home/senid/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /home/senid/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

cause this code

``` ruby
def _associate(klass, *attrs)
...
     if association.is_a?(JSONAPI::Association::HasOne)
     define_method foreign_key do
      @model.method(foreign_key).call
    end unless method_defined?(foreign_key)
...
end
```

defines correct method only for ActiveRecord belongs_to type of relation.
for ActiveRecord has_one it fails

i find a workaround:

``` ruby
class AuthorResource < JSONAPI::Resource
  has_one :author_detail

  def author_detail_id
    model.author_detail.try!(:id)
  end
end
```

but i think has_one in resources should have some option that allows to change it's behaviour

### PR DESCRIPTION
**Pull request by lgebhardt**
Some background: In JR most has_one associations are really rails belongs_to associations. In the early JR releases this didn't matter and we choose to simplify the resources. However some recent changes have led to the code needing to know the underlying association type. The most common one to one association is really a belongs_to (where the foreign key is on the resource where the association is being declared).

This is an alternative proposal to #305, and intended to fix #300. Instead of requiring most `has_one` associations to be renamed to `belongs_to`, a `foreign_key_on` option is used to indicate that the foreign resource needs to be looked up to retrieve the identifier. In reviewing #305 with fresh eyes I have found we really should, for consistency, have separate operations and callbacks for updating the has_one vs belongs_to associations. But I don't think that level of granularity improves the code base. But without it it seems incomplete.
#305 style:

``` ruby
class PostResource < JSONAPI::Resource
  attribute :title, :body
  belongs_to :author
  has_one :post_details
end
```

This PR's style

``` ruby
class PostResource < JSONAPI::Resource
  attribute :title, :body
  has_one :author
  has_one :post_details, foreign_key_on: :related_resource
end
```

I'm favoring this alternative since it requires the least changes to peoples' existing code. There are few differences between a has_one and a belongs_to as far as JR is concerned. Since has_one associations are not that common it seems the foreign_key_on flag is the least intrusive way to make this work. 

The main downside is the associations will continue to not match the underlying model declarations. 

Opinions are welcome.

### CODE REVIEW

**Comment by barelyknown** [comment]
I think that it's smart that you're thinking about minimizing the amount of change required for users, but I'm not sure that it's worth it in this case. New Rails programmers often have trouble understanding the difference between `has_one` and `belongs_to` relationships, and I'm afraid that if we don't match Rails convention here it'll confuse users more than the avoiding the pain of migrating to the new syntax is worth.

**Comment by barelyknown** [comment]
975-x-696

**Comment by lgebhardt** [comment]
@barelyknown Thanks for your opinion (and for pointing out my poorly named branch - what was I thinking?). 

If we go to separate `belongs_to` and `has_one` associations do you see us also needing separate operations and callbacks? I'm tempted to keep those lumped together under has_one, but maybe that's shortsighted.

**Comment by barelyknown** [comment]
My hunch is that we should have separate operations and callbacks, but I haven't come across that specific need.

**Comment by lgebhardt** [comment]
After chatting with @dgeb I've changed the option name and updated the PR description.

**Comment by dgeb** [comment]
In the pre-1.0 days, I don't mind introducing breaking changes if it improves the API. In this case, I actually prefer using `has_one` to cover both scenarios, since the location of the foreign key is an implementation detail that's irrelevant to how a relationship is displayed at the API layer. Consider that resources don't have to be backed by ActiveRecord or even a relational DB.

I'm ok with the `foreign_key_on` option, but open to suggestions (other than `has_one: direction` :stuck_out_tongue_winking_eye:)

**Comment by barelyknown** [comment]
`foreign_key_on: :related_resource` seems good to me.

**Comment by ggordon** [comment]
What do you think about using a single method like `association` instead of  the `belongs_to`, `has_one` or `has_many` methods?

```
belongs_to -> association :author, multiplicity: :one
has_one    -> association :priority, multiplicity: :one, foreign_key_on: :priority
has_many   -> association :comments, multiplicity: :many
```

This could be further simplified if multiplicity defaulted to :one. Not sure if `association` or `multiplicity` are the best names, but the idea is to just have one method instead of two/three.

**Comment by lgebhardt** [comment]
@ggordon I think that might be a step too far. I like the syntax of has_one vs has_many, if only because I'm familiar with it. I suspect that will be case for most Rails developers. 

However if we were to rename the methods we would probably want to adopt the naming as it's used in the JSON API specification. That would be "relationship" instead of "association".

I'm not sure I like this, but how about the following?

```
belongs_to -> relationship :author, to: :one
has_one    -> relationship :priority, to: :one, foreign_key_on: :priority
has_many   -> relationship :comments, to: :many
```

**Comment by dgeb** [comment]
I don't like the verbosity of `:related_resource`, and I don't like having to repeat the relationship name.

My preference is to go with `foreign_key_on: :related` and `foreign_key_on: :self`

**Comment by dgeb** [comment]
I could see supporting both `has_one` and `has_many` as aliases to `relationship`, which would be the most general form.

**Comment by lgebhardt** [comment]
Ok, I'll make those changes.

**Comment by dgeb** [comment]
Thanks @lgebhardt!

**Comment by lgebhardt** [comment]
I added the `relationship` method and renamed the `foreign_key_on` option to `related`.

The last commit is a large set of changes. I used this as an opportunity to refactor "associations" into "relationships". I've been wanting to do this since JSON API started using the relationships top level key. I expect a bit of pain for people with overrides of some resource methods and callbacks. I think it improves the understandability of the project, and in the long run it should pay off. I hope you all agree.

File: test/unit/serializer/link_builder_test.rb [hunk 1]
```diff
@@ -98,11 +98,11 @@ def test_relationships_self_link_for_regular_app
 
     builder       = JSONAPI::LinkBuilder.new(config)
     source        = Api::V1::PersonResource.new(@steve)
-    association   = JSONAPI::Association::HasMany.new("posts", {})
+    relationship   = JSONAPI::Relationship::ToMany.new("posts", {})
```
Comment (hinshun) [inline test/unit/serializer/link_builder_test.rb]: the '='s across this file are misaligned now, a small style issue but figure i'll just point it out in case you weren't aware.

Comment (lgebhardt) [inline test/unit/serializer/link_builder_test.rb]: Thank you. I hadn't noticed. I'll get it cleaned up.

**Comment by dgeb** [comment]
Fantastic job @lgebhardt :shipit:
