### PR TITLE
Adds tests and fix for complex include missing relationships

### LINKED ISSUE #802: Circular inclusions can lose data
Verified on `0.8.0.beta2` in a simple testing app with three models: `Box`, `Thing`, `User`, where:

```
boxes ------> things
       many    | ^
           one | |
               | | many
               v |
              users
```

When requesting

```
/api/boxes?include=things,things.user
```

everything looks ok, but when requesting one level deeper for

```
/api/boxes?include=things,things.user,things.user.things
```

so that the `User` includes its `Thing`s, some of the thing-to-user relationship data disappears.

It seems that there's a depth-first search that explores the first thing-to-user relationship via the first `Thing` it encounters and finds the remaining `Thing`s  through the user-to-things relationship without including the thing-to-user relationship. Requesting

```
/api/boxes?include=things,things.user,things.user.things,things.user.things.user
```

with yet another circular reference resolves this, corroborating the depth-first hypothesis.

An example: one `Box` with two `Thing`s, each with the same `User`. Requests and results of `included` list (with `links` and `box` relationship removed):

```
# /api/boxes?include=things,things.user
...
    {
      "id": "1",
      "type": "things",
      "relationships": {
        "user": {
          "data": {
            "type": "users", "id": "1"
          }
        }
      }
    },
    {
      "id": "2",
      "type": "things",
      "relationships": {
        "user": {
          "data": {
            "type": "users", "id": "1"
          }
        }
      }
    },
    {
      "id": "1",
      "type": "users",
      "relationships": {
        "things": {}
      }
    }
...
```

```
...
# /api/boxes?include=things,things.user,things.user.things
    {
      "id": "1",
      "type": "things",
      "relationships": {
        "user": {}
      }
    },
    {
      "id": "2",
      "type": "things",
      "relationships": {
        "user": {
          "data": {
            "type": "users", "id": "1"
          }
        }
      }
    },
    {
      "id": "1",
      "type": "users",
      "relationships": {
        "things": {
          "data": [
            {
              "type": "things", "id": "1"
            },
            {
              "type": "things", "id": "2"
            }
          ]
        }
      }
    }
...
```

...`Thing` loses its `User` data. To get both the things-to-user data and also the user-to-things data, I am having to request:

```
# /api/boxes?include=things,things.user,things.user.things,things.user.things.user
...
    {
      "id": "1",
      "type": "things",
      "relationships": {
        "user": {
          "data": {
            "type": "users", "id": "1"
          }
        }
      }
    },
    {
      "id": "2",
      "type": "things",
      "relationships": {
        "user": {
          "data": {
            "type": "users", "id": "1"
          }
        }
      }
    },
    {
      "id": "1",
      "type": "users",
      "relationships": {
        "things": {
          "data": [
            {
              "type": "things", "id": "1"
            },
            {
              "type": "things", "id": "2"
            }
          ]
        }
      }
    }
...
```

My testing app setup:

```
Rails.application.routes.draw do
  namespace :api do
    jsonapi_resources :boxes
  end
end

class Box < ActiveRecord::Base
  has_many :things
end

class Thing < ActiveRecord::Base
  belongs_to :box
  belongs_to :user
end

class User < ActiveRecord::Base
  has_many :things
end

class Api::BoxesController < ApplicationController
  include JSONAPI::ActsAsResourceController
end

class Api::BoxResource < JSONAPI::Resource
  has_many :things
end

class Api::ThingResource < JSONAPI::Resource
  has_one :box
  has_one :user
end

class Api::UserResource < JSONAPI::Resource
  has_many :things
end
```

### PR DESCRIPTION
**Pull request by lgebhardt**
Adds the ability to detect when existing serialized resource representations are missing relationships based on include directives. This should allow for a composite representation adhering to the agregate include rules for all levels where the same resource is encountered, but may be serialized differently.

Adds the tests for master using `assert_cacheable_get` based off https://github.com/drakedowsett/jsonapi-resources-issues/tree/issue-1 from #802

Fixes #802

### CODE REVIEW

**Comment by lgebhardt** [comment]
Updated to use a new `volatile` flag in the `include_directives`. When encountered by the serializer resources will be serialized according to the current include settings and merged with the existing serialized resource representations. This should allow for a composite representation adhering to the include rules for each level where the resource is encountered.

This PR is still not ready for merging as the `volatile` flag is being applied too broadly, which will hurt performance.

File: lib/jsonapi/resource_serializer.rb [hunk 1]
```diff
@@ -467,14 +462,29 @@ def set_primary(type, id)
...
-    def add_included_object(obj_hash, primary = false)
-      is_cached = obj_hash.is_a?(JSONAPI::CachedResourceFragment)
-      type = is_cached ? obj_hash.type : obj_hash['type']
-      id = is_cached ? obj_hash.id : obj_hash['id']
+    def add_resource(source, include_directives, primary = false)
+      type = source.is_a?(JSONAPI::CachedResourceFragment) ? source.type : source.class._type
+      id = source.id
 
       @included_objects[type] ||= {}
-      @included_objects[type][id] = { primary: primary, object_hash: obj_hash }
```
Comment (dgeb) [inline lib/jsonapi/resource_serializer.rb:477]: Perhaps change `@included_objects` to `@included_resources`?

Comment (lgebhardt) [reply lib/jsonapi/resource_serializer.rb:477]: They're not resources, but rather serialized hashes on resources (made with certain settings).
